axon:
  eventhandling:
    processors:
      keycloak_user_ids:
        mode: subscribing

server:
  error:
    include-stacktrace: never

policy:
  refund-deadline-days: 30
  commission-percentage: 0.1
